import { fileURLToPath, URL } from 'url'
import vue from '@vitejs/plugin-vue'
import { defineConfig } from 'vite'

export default defineConfig(() => {
  return {
    build: {
      rollupOptions: {
        // This is for the code generated by decorators. If we don't specify this,
        // it defaults to globalThis, which older android phones won't understand.
        context: 'window'
      },
      sourcemap: process.env.NODE_ENV !== 'production',
      target: 'es2017'
    },
    plugins: [vue()],
    resolve: {
      alias: {
        // eslint-disable-next-line @typescript-eslint/naming-convention
        '@': fileURLToPath(new URL('./src', import.meta.url))
      }
    }
  }
})
