platform :ios, '11.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor/ios@2.4.3_@capacitor+core@2.4.3/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor/ios@2.4.3_@capacitor+core@2.4.3/node_modules/@capacitor/ios'
  pod 'WsCapacitorSecureStorage', :path => '../../../ws-capacitor-secure-storage'
  # Do not delete
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end
